# Generated by Django 5.2

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('NonSoc', '0002_securityawareness_securityrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityRequestResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_responses', to=settings.AUTH_USER_MODEL)),
                ('security_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='NonSoc.securityrequest')),
            ],
        ),
        migrations.AddField(
            model_name='securityrequest',
            name='category',
            field=models.CharField(choices=[('access', 'Access Request'), ('incident', 'Security Incident'), ('vulnerability', 'Vulnerability Report'), ('question', 'General Question'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='securityrequest',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='securityrequest',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='securityrequest',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('pending_info', 'Pending Info'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='new', max_length=15),
        ),
    ]
