# Generated by Django 5.2 on 2025-04-17 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NonSoc', '0003_securityawareness_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='awarenessquestion',
            name='module',
        ),
        migrations.RemoveField(
            model_name='moduleattempt',
            name='questions_seen',
        ),
        migrations.RemoveField(
            model_name='moduleattempt',
            name='module',
        ),
        migrations.RemoveField(
            model_name='moduleattempt',
            name='user',
        ),
        migrations.RemoveField(
            model_name='securityawareness',
            name='course',
        ),
        migrations.RemoveField(
            model_name='securityawareness',
            name='users_completed',
        ),
        migrations.RemoveField(
            model_name='securityrequest',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='usernotification',
            name='related_object_id',
        ),
        migrations.RemoveField(
            model_name='usernotification',
            name='related_object_type',
        ),
        migrations.AddField(
            model_name='usernotification',
            name='link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='securityrequest',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='securityrequest',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='new', max_length=15),
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='notification_type',
            field=models.CharField(choices=[('course', 'Course'), ('security', 'Security'), ('achievement', 'Achievement'), ('awareness', 'Awareness Module'), ('general', 'General')], default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='AnswerChoice',
        ),
        migrations.DeleteModel(
            name='AwarenessQuestion',
        ),
        migrations.DeleteModel(
            name='ModuleAttempt',
        ),
        migrations.DeleteModel(
            name='SecurityAwareness',
        ),
    ]
