# Generated by Django 5.2 on 2025-04-09 19:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_password_change',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nonsocuser',
            name='completed_trainings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nonsocuser',
            name='job_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='nonsocuser',
            name='security_awareness_level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='socuser',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socuser',
            name='certifications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator('^[\\w.@+-]+$', 'Enter a valid username.')]),
        ),
        migrations.AlterField(
            model_name='nonsocuser',
            name='department',
            field=models.CharField(choices=[('HR', 'Human Resources'), ('IT', 'Information Technology'), ('FIN', 'Finance'), ('MKT', 'Marketing'), ('OPS', 'Operations'), ('SEC', 'Security'), ('DEV', 'Development'), ('OTHER', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='socuser',
            name='role',
            field=models.CharField(choices=[('analyst', 'SOC Analyst'), ('engineer', 'SOC Engineer'), ('manager', 'SOC Manager'), ('lead', 'SOC Lead'), ('architect', 'Security Architect'), ('researcher', 'Security Researcher'), ('admin', 'SOC Administrator')], max_length=50),
        ),
    ]
