# Generated by Django 5.2 on 2025-04-09 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customuser_last_password_change_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('soc', 'SOC User'), ('non_soc', 'Non-SOC User')], default='non_soc', max_length=10),
        ),
        migrations.AlterField(
            model_name='nonsocuser',
            name='department',
            field=models.CharField(choices=[('HR', 'Human Resources'), ('IT', 'Information Technology'), ('FIN', 'Finance'), ('MKT', 'Marketing'), ('OPS', 'Operations'), ('SEC', 'Security'), ('DEV', 'Development'), ('OTHER', 'Other')], default='OTHER', max_length=100),
        ),
        migrations.AlterField(
            model_name='socuser',
            name='role',
            field=models.CharField(choices=[('analyst', 'SOC Analyst'), ('engineer', 'SOC Engineer'), ('manager', 'SOC Manager'), ('lead', 'SOC Lead'), ('architect', 'Security Architect'), ('researcher', 'Security Researcher'), ('admin', 'SOC Administrator')], default='analyst', max_length=50),
        ),
    ]
