# Generated by Django 5.2 on 2025-04-09 20:00

import django.db.models.deletion
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Soc', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityalert',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='securityalert',
            name='source',
            field=models.CharField(default='internal', max_length=100),
        ),
        migrations.AlterField(
            model_name='securityincident',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_security_incidents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='securityincident',
            name='reported_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reported_security_incidents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='securityreport',
            name='content',
            field=tinymce.models.HTMLField(default=''),
        ),
        migrations.AlterField(
            model_name='securityreport',
            name='report_type',
            field=models.CharField(choices=[('incident', 'Incident Report'), ('threat', 'Threat Assessment'), ('vulnerability', 'Vulnerability Assessment'), ('audit', 'Security Audit'), ('metrics', 'Security Metrics'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='securityreport',
            name='summary',
            field=models.TextField(default=''),
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(default='')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_soc_incidents', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_soc_incidents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IncidentResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('action_taken', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='Soc.incident')),
                ('responder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
